from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from scidiscovery.artifact_agent.interfaces.mcp_root import (
    ROOT_TOOLS as ROOT_MCP_TOOLS,
)
from scidiscovery.artifact_agent.interfaces.mcp_worker import (
    WORKER_TOOLS as WORKER_MCP_TOOLS,
)

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

from .common import (
    GenerationReport,
    PlatformConflictError,
    absolute_project_root,
    commit_text_files,
    managed_block,
)
from .roles import (
    RoleDefinition,
    load_roles,
    load_scheduler_prompt,
    render_worker_prompt,
)


CONFIG_BEGIN = "# BEGIN SCIDISCOVERY MANAGED MCP"
CONFIG_END = "# END SCIDISCOVERY MANAGED MCP"
PROMPT_BEGIN = "<!-- BEGIN SCIDISCOVERY SCHEDULER -->"
PROMPT_END = "<!-- END SCIDISCOVERY SCHEDULER -->"
SCHEDULER_TOOLS = tuple(tool.name for tool in ROOT_MCP_TOOLS)
WORKER_TOOLS = tuple(tool.name for tool in WORKER_MCP_TOOLS)
CODEX_DISPATCH_INSTRUCTIONS = """

On Codex, dispatch every ready task with `spawn_agent`. Use the `agent_type`
returned by control, set `fork_turns="none"`, and ask the child to complete the
assignment already queued for its worker process. Do not pass task metadata in
the message. The child must finish through `worker_finalize_file` before the
scheduler uses its bounded signal.

Human decisions are made directly in the loopback approval UI. Give the user
the exact review URL returned by the relevant approval-request tool, then read
only `approval_status`; never convert chat text into a decision or call an
approval write operation on the user's behalf.
""".strip()


def initialize(
    project_root: Path | str,
    *,
    python_executable: Path | str | None = None,
    python_path: Path | str | None = None,
    control_socket: Path | str,
    worker_socket: Path | str,
    codex_config_root: Path | str | None = None,
    dry_run: bool = False,
) -> GenerationReport:
    root = absolute_project_root(project_root)
    python = _absolute_python_executable(
        python_executable or sys.executable
    )
    module_path = (
        _absolute_path(python_path)
        if python_path is not None
        else Path(__file__).resolve().parents[2]
    )
    socket_path = _absolute_path(control_socket)
    worker_socket_path = _absolute_path(worker_socket)
    config_root = _absolute_path(codex_config_root or root / ".codex")

    desired: dict[Path, str] = {}
    exclusive: set[Path] = set()
    markers: dict[Path, str] = {}
    for role in load_roles():
        path = config_root / "agents" / f"{role.name}.toml"
        desired[path] = _role_toml(
            role,
            python=python,
            python_path=module_path,
            worker_socket=worker_socket_path,
        )
        exclusive.add(path)
        markers[path] = "# Generated by SciDiscovery."

    config_path = config_root / "config.toml"
    current_config = _read(config_path)
    _reject_unmanaged_server(current_config)
    runtime_config = _runtime_config_toml(current_config)
    server_config = _proxy_server_toml(
        python=python, socket_path=socket_path, python_path=module_path
    )
    desired[config_path] = managed_block(
        current_config,
        begin=CONFIG_BEGIN,
        end=CONFIG_END,
        body="\n\n".join(
            part for part in (runtime_config, server_config) if part
        ),
    )
    tomllib.loads(desired[config_path])

    prompt_path = root / "AGENTS.md"
    desired[prompt_path] = managed_block(
        _read(prompt_path),
        begin=PROMPT_BEGIN,
        end=PROMPT_END,
        body=f"{load_scheduler_prompt().rstrip()}\n\n"
        f"{CODEX_DISPATCH_INSTRUCTIONS}\n",
    )
    return commit_text_files(
        platform="codex",
        project_root=root,
        desired=desired,
        exclusive=frozenset(exclusive),
        exclusive_markers=markers,
        dry_run=dry_run,
    )


def _role_toml(
    role: RoleDefinition,
    *,
    python: Path,
    python_path: Path | None,
    worker_socket: Path,
) -> str:
    prompt = render_worker_prompt(role, python_executable=python)
    lines = [
        "# Generated by SciDiscovery. Re-run `scid init codex` to update.",
        f"name = {_quote(role.name)}",
        f"description = {_quote(role.description)}",
        'sandbox_mode = "read-only"',
        'web_search = "live"',
        f"developer_instructions = {_quote(prompt)}",
        "",
        "[tools]",
        "view_image = true",
        'web_search = { context_size = "high" }',
        "",
        _worker_proxy_server_toml(
            python=python,
            python_path=python_path,
            socket_path=worker_socket,
            role=role.name,
        ),
    ]
    content = "\n".join(lines).rstrip() + "\n"
    tomllib.loads(content)
    return content


def _proxy_server_toml(
    *, python: Path, socket_path: Path, python_path: Path | None
) -> str:
    args = (
        "-m",
        "scidiscovery.artifact_agent.interfaces.mcp_proxy",
        "--socket",
        str(socket_path),
    )
    return "\n".join(
        (
            "[mcp_servers.scidiscovery]",
            f"command = {_quote(str(python))}",
            "args = [" + ", ".join(_quote(value) for value in args) + "]",
            "enabled = true",
            "required = true",
            "enabled_tools = ["
            + ", ".join(_quote(tool) for tool in SCHEDULER_TOOLS)
            + "]",
            'default_tools_approval_mode = "approve"',
            _toml_env(
                {
                    "PYTHONNOUSERSITE": "1",
                    "SCIDISCOVERY_PRINCIPAL": "service",
                    **({"PYTHONPATH": str(python_path)} if python_path else {}),
                }
            ),
        )
    )


def _worker_proxy_server_toml(
    *,
    python: Path,
    python_path: Path | None,
    socket_path: Path,
    role: str,
) -> str:
    args = (
        "-m",
        "scidiscovery.artifact_agent.interfaces.mcp_worker_proxy",
        "--socket",
        str(socket_path),
        "--worker-id",
        role,
    )
    return "\n".join(
        (
            "[mcp_servers.scidiscovery]",
            f"command = {_quote(str(python))}",
            "args = [" + ", ".join(_quote(value) for value in args) + "]",
            "enabled = true",
            "required = true",
            "enabled_tools = ["
            + ", ".join(_quote(tool) for tool in WORKER_TOOLS)
            + "]",
            'default_tools_approval_mode = "approve"',
            _toml_env(
                {
                    "PYTHONNOUSERSITE": "1",
                    "SCIDISCOVERY_PRINCIPAL": "agent",
                    "SCIDISCOVERY_ROLE": role,
                    **({"PYTHONPATH": str(python_path)} if python_path else {}),
                }
            ),
        )
    )


def _toml_env(values: dict[str, str]) -> str:
    entries = ", ".join(
        f"{key} = {_quote(value)}" for key, value in sorted(values.items())
    )
    return f"env = {{ {entries} }}"


def _reject_unmanaged_server(current: str) -> None:
    if not current.strip() or CONFIG_BEGIN in current:
        return
    try:
        parsed = tomllib.loads(current)
    except tomllib.TOMLDecodeError as error:
        raise PlatformConflictError(
            f"existing Codex config is invalid: {error}"
        ) from error
    servers = parsed.get("mcp_servers", {})
    if isinstance(servers, dict) and "scidiscovery" in servers:
        raise PlatformConflictError(
            "existing Codex config owns mcp_servers.scidiscovery"
        )


def _runtime_config_toml(current: str) -> str:
    unmanaged = _without_managed_block(current)
    try:
        parsed = tomllib.loads(unmanaged)
    except tomllib.TOMLDecodeError as error:
        raise PlatformConflictError(
            f"existing Codex config is invalid: {error}"
        ) from error

    blocks: list[str] = []
    features = parsed.get("features")
    if features is None:
        blocks.append("[features]\nmulti_agent = true")
    elif not isinstance(features, dict) or features.get("multi_agent") is False:
        raise PlatformConflictError(
            "existing Codex [features] explicitly disables multi_agent"
        )

    agents = parsed.get("agents")
    if agents is None:
        blocks.append(
            "[agents]\n"
            "enabled = true\n"
            "max_concurrent_threads_per_session = 3"
        )
    elif not isinstance(agents, dict) or agents.get("enabled") is False:
        raise PlatformConflictError(
            "existing Codex [agents] explicitly disables agents"
        )
    return "\n\n".join(blocks)


def _without_managed_block(current: str) -> str:
    if CONFIG_BEGIN not in current:
        return current
    start = current.index(CONFIG_BEGIN)
    try:
        end = current.index(CONFIG_END, start) + len(CONFIG_END)
    except ValueError as error:
        raise PlatformConflictError(
            "existing Codex managed MCP block is unterminated"
        ) from error
    return (current[:start] + current[end:]).strip()


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _absolute_python_executable(value: Path | str) -> Path:
    expanded = Path(value).expanduser()
    return Path(os.path.abspath(os.fspath(expanded)))


def _absolute_path(value: Path | str) -> Path:
    return Path(os.path.abspath(os.fspath(Path(value).expanduser())))
