"""Stable declarations exposed to SciDiscovery operation plugins."""

from .spec import (
    AgentLifecycleProtocol,
    AgentLifecycleTool,
    ApprovalContract,
    ApprovalOption,
    CallableComponent,
    CollectionSpec,
    CompleteTransformFamilySpec,
    ComponentRef,
    ComponentSpec,
    ExecutorRef,
    InputAdmissionSpec,
    InputPortSpec,
    LimitsSpec,
    NativeToolPolicy,
    NetworkPolicy,
    OperationDescription,
    OperationSpec,
    OutputPortSpec,
    PluginDefinition,
    PluginDependency,
    ReviewSpec,
    WorkspaceContract,
    canonical_digest,
    canonical_json,
)
from .tooling import WorkerToolDefinition

__all__ = [
    "AgentLifecycleProtocol",
    "AgentLifecycleTool",
    "ApprovalContract",
    "ApprovalOption",
    "CallableComponent",
    "CollectionSpec",
    "CompleteTransformFamilySpec",
    "ComponentRef",
    "ComponentSpec",
    "ExecutorRef",
    "InputAdmissionSpec",
    "InputPortSpec",
    "LimitsSpec",
    "NativeToolPolicy",
    "NetworkPolicy",
    "OperationDescription",
    "OperationSpec",
    "OutputPortSpec",
    "PluginDefinition",
    "PluginDependency",
    "ReviewSpec",
    "WorkspaceContract",
    "WorkerToolDefinition",
    "canonical_digest",
    "canonical_json",
]
